### ISSUE TITLE
Sensor Error: UNDERFLOW

### ISSUE THREAD

**Issue by OmarAlkassab** [bertmelis/esp32DHT#4] opened 2019-11-29 18:51 UTC
I have tested, the library on esp32. I tried the example for DHT11 and it works perfectly. But when I integrate the code with my big code it return first time TO and then return always UNDERFLOW.
Any help please?

**Comment by bertmelis** [comment] 2020-11-18 09:19
I can reproduce. No solution in sight though.

**Comment by bertmelis** [comment] 2020-11-18 10:01
Update:
- every very first capture (after powering up) fails
- all next captures work fine

Setup:
esp32 devkit v1, directly connected via jumper wires to a DTH22, no pullup, powering on 3.3V. Parallel a logic analyzer to compare.

I use the example code with ONE BIG GOTCHA, I use the GPIO number instead of the pin number in the `sensor.setup()`.

**Comment by bertmelis** [comment] 2020-11-18 10:20
I haven't tested on big projects. There might be an issue with task switching etc that causes some delay so it misses the first pulse. 

Please hold on, I'm rethinking the design of the lib.

**Comment by bertmelis** [comment] 2020-11-27 09:54
Going to close this issue. I can't reproduce anymore. Readme has been updated to include known limitations. Feel free to reopen if the problem persists.

**Closed as completed by bertmelis** 2020-11-27 09:54 UTC

**Comment by gnampf89** [comment] 2021-01-02 16:15
It works much better (at least for DHT22) when I shift half a period when `numItems` is 41. No errors at all, even on the very first reading (2s after power on). Without this the first 3..4 (sometimes more) readings would fail.


```
void DHT::_decode(rmt_item32_t *data, int numItems)
{
  uint8_t start = 1;
  if (numItems == 41)
  {
    start = 0;
  }
  if (numItems < 41)
  {
    _status = 5;
  }
  else if (numItems > 42)
  {
    _status = 6;
  }
  else if ((data[0].duration0 + data[0].duration1) < 140 && (data[0].duration0 + data[0].duration1) > 180)
  {
    _status = 2;
  }
  else
  {
    for (uint8_t i = start; i < numItems - 1; ++i)
    { // don't include tail
      uint8_t pulse = data[i].duration0 + data[i].duration1;
      if (!start)
      {
        // shift detection window half a period
        pulse = data[i].duration1 + data[i + 1].duration0;
      }
      if (pulse > 55 && pulse < 145)
      {
        int j = (i - start) / 8;
        _data[j] <<= 1; // shift left
        if (pulse > 120)
        {
          _data[j] |= 1;
        }
      }
      else
      {
        _status = 3; // DATA error
        return;
      }
    }
    if (_data[4] == ((_data[0] + _data[1] + _data[2] + _data[3]) & 0xFF))
    {
      _status = 0;
    }
    else
    {
      _status = 4; // checksum error
    }
  }
}
```

**Comment by gnampf89** [comment] 2021-01-02 16:26
Found my DHT11, it works, too.

**Comment by mathieucarbou** [comment] 2023-09-28 00:01
Hello,
I am using a DHT22 sensor since a few weeks, and suddenly I also get this error. 
This patch did not work for me.

**Comment by mathieucarbou** [comment] 2023-09-28 00:48
And it is working fine with this library: https://github.com/mathieucarbou/DHT-sensor-library/
